{% set name = "textx" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37b4f0c455452e27cc0f13d40777b5d20549eaa871311b26e2ed83c019456692

build:
  entry_points:
    - textx = textx.cli:textx
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - flit-core >=3.8.0,<4
    - pip
    - python {{ python_min }}
  run:
    - arpeggio >=2.0.0
    - click >=7.0,<9.0
    - importlib-metadata
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - textx
    - textx.scoping
    - textx.cli

  commands:
    - pip check
    - textx --help
    # This test file is causing problem can't easily exclude by pytest commands
    - rm tests/functional/test_objcrossref_positions.py
    - pip install -e tests/functional/subcommands/example_project --no-deps
    - pip install -e tests/functional/registration/projects/types_dsl --no-deps
    - pip install -e tests/functional/registration/projects/data_dsl --no-deps
    - pip install -e tests/functional/registration/projects/flow_dsl --no-deps
    - pip install -e tests/functional/registration/projects/flow_codegen --no-deps
    # Need to skip a couple test before upstream excluded some test files from sdist
    - pytest -vvv --capture=tee-sys -k "not test_examples" tests/functional
  requires:
    - attrs
    - html5lib
    - jinja2
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: http://textx.github.io/textX/
  dev_url: https://github.com/textX/textX
  summary: Meta-language for DSL implementation inspired by Xtext
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
