schema_version: 1

context:
  name: textx
  version: "4.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: a7b15a4698b503edde631d5227c0d0f6024898a86a7924b5fc741973305f9286

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - textx = textx.cli:textx

requirements:
  host:
    - flit-core >=3.8.0,<4
    - pip
    - python ${{ python_min }}.*
  run:
    - arpeggio >=2.0.0
    - click >=7.0,<9.0
    - importlib-metadata
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - textx
        - textx.scoping
        - textx.cli
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - textx --help
      
about:
  summary: Meta-language for DSL implementation inspired by Xtext
  license: MIT
  license_file: LICENSE.txt
  homepage: http://textx.github.io/textX/
  repository: https://github.com/textX/textX

extra:
  recipe-maintainers:
    - thewchan
